### ISSUE TITLE
I can't craft the blocks

### ISSUE THREAD

**Issue by zychology** [Yamahari/ILikeWood-1.15#15]
Whenever I try to craft (for example : the mahogany chest) the crafting recipe does not show up and If i want it added to my world I need to use creative. The vanilla block versions work but the modded doesn't.  I play on 1.15.2.

**Comment by Yamahari** [comment]
Install the datapack that you can find undee additional files x)

**Comment by zychology** [comment]
oops haha.. do i just put the additional files in the mods folder?

**Comment by Yamahari** [comment]
in your world folder under datapacks :) you can check in-game if it worked with "/datapack list" i think

**Comment by PCat4L** [comment]
do we just copy-paste ? because that's what i did but still can't see recipes.

Using Biomes O' Plenty btw.

**Comment by Yamahari** [comment]
just put the zip into the datapack folder

**Comment by PCat4L** [comment]
Ohhh silly me! I was extracting then pasting, tysm!
