### ISSUE TITLE
Every crafting table variant is a tab in JEI crafting window

### ISSUE THREAD

**Issue by jengendler** [Yamahari/ILikeWood-1.15#16]
When looking up any item's crafting recipe in JEI, every single wood variant crafting table shows as a tab on the left making the screen overwhelming. I'm not sure if this is default behavior in previous versions, but it would be nice if there was just one full block crafting table since these are just variants of the block that all behave the same way.

Love the BoP support on this mod btw!

**Comment by Yamahari** [comment]
I'll have a go once I get back working on this mod! :)

**Comment by Yamahari** [comment]
done in ilikewood-1.16.2-3.0.4.0 :)
