### ISSUE TITLE
This mod crashes my game with no crash report (version: 1.15.2)

### ISSUE THREAD

**Issue by vinnyg0621** [Yamahari/ILikeWood-1.15#19]
the debug.log:
[debug.log](https://github.com/Yamahari/ILikeWood-1.15/files/5125872/debug.log)

**Comment by Yamahari** [comment]
try without optifine

**Comment by vinnyg0621** [comment]
ok

**Comment by ghost** [comment]
I use Forge 31.2.36, preview_OptiFine_1.15.2_HD_U_G1_pre30 and ILikeWood 1.15.2-2.2.2.0 and everything runs fine

Does it crash during load or during gameplay?
