### ISSUE TITLE
1.15.2 - BoP walls don't attach to each other

### ISSUE THREAD

**Issue by ghost** [Yamahari/ILikeWood-1.15#20]
Forge: 31.2.36
ILikeWood: 1.15.2-2.2.2.0

The Biomes O Plenty wall types, such as Magic wall and Cherry wall, do not attach to each other at any angle. The vanilla walls, Birch etc, are perfect

See pic:  [https://imgur.com/a/9FFfq5c](https://imgur.com/a/9FFfq5c)

**Comment by Yamahari** [comment]
do you have the datapack for BoP installed? :P

**Comment by ghost** [comment]
Well that fixed it.  I just assumed the datapack was for recipe changes.

Thank you

I use my own datapack to adjust recipes/loottables and advancements - I've copied the minecraft/tags/blocks/walls.json to my datapack and all is working fine
