### ISSUE TITLE
Biomes O' Plenty Addon 1.15.2

### ISSUE THREAD

**Issue by HackX17** [Yamahari/ILikeWood-1.15#21]
According to the curseforge page, the mod has compatibilty for Biome O' Plenty, but whenever I try to craft anything with the wood of the biome it doesn't work. Taking the wood variants from JEI works but in survival even if you place them, when you break them they drop nothing, it's like the block is there with just it's function and texture. I tried to look for an addon that has to be downloaded separetely but the page just gives a link to the biomes o' plenty mod.

**Comment by Yamahari** [comment]
you need to install the datapack in your world's datapack folder. You can find it under "Additional Files" :) If you still can't get it to work let me know

**Comment by Yamahari** [comment]
closed due to no further detaills
