### ISSUE TITLE
Is there an API or some way I can add wood types of my mod to work with this mod?

### ISSUE THREAD

**Issue by rehwinkel** [Yamahari/ILikeWood-1.15#23]
I have a [mod](https://www.curseforge.com/minecraft/mc-mods/treemendous) that adds plenty of wood types to the game. A user asked if I could add support for the "I Like Wood" mod, but it seems like there is no IMC or API for that. 

Essentially I'm asking if there is an API, and if not, I would like to suggest adding one for other mods to be able to easily make their woods work with this mod.

**Comment by Yamahari** [comment]
There's no api at the moment, that'd require quite some refactoring, in the meantime I can have a look at manually adding your mod compat

**Comment by rehwinkel** [comment]
I'm gonna look into making a PR to add my mod's wood types to this mod.

**Comment by Yamahari** [comment]
i am working on an API on branch "plugin" now :)

**Comment by Yamahari** [comment]
hey the API should be useable now, but it needs testing, can you try to use it with your mod? If you're not sure how to use something feel free to ask

**Comment by OGitsBoondock** [comment]
I may give Oh the biomes you'll go a try, that mod is excellent and underserved with compat unfortunately.  I am considering just changing the references in the recipes to the byg version but need to know if you store the textures internally or what not.  I unfortunately cannot code but I can learn to use an API as I at least understand .json files

**Comment by Yamahari** [comment]
Once I release the new version alongside with api, there will also be a plugin for BoP that you can use as an example for other plugins

**Comment by OGitsBoondock** [comment]
> Once I release the new version alongside with api, there will also be a plugin for BoP that you can use as an example for other plugins

 I look forward to it!

**Comment by Yamahari** [comment]
the api is ready to be used, you can see https://github.com/Yamahari/ILikeWood-BiomesOPlenty-Plugin, how it works, if something is unclear, tell me :)
