### ISSUE TITLE
Question / Suggestion

### ISSUE THREAD

**Issue by DerekM07** [Yamahari/ILikeWood-1.15#27]
Any intention to add Biomes O' Plenty wood signs in future versions? (redwood sign, fir sign, etc.)

I was looking for a mod that adds these in MC v1.16.4 and surprisingly I can't find one.

I realize text may not be legible on some, but half the time builders use these is for detailing, leaving them blank.

Thank you for consideration.

**Comment by Yamahari** [comment]
I was under the assumption that biomes o' plenty already has their own signs?

**Comment by DerekM07** [comment]
They don't, I searched the JEI item list for "sign". =(

**Comment by Yamahari** [comment]
well if I find the time I can have a go at it again, I was actually working on improved signs, that can also hang from the ceiling, a while ago [screenshot](https://cdn.discordapp.com/attachments/600285083617853454/795757435871821854/2019-06-30_13.12.33.png)

**Comment by DerekM07** [comment]
If they can do that too, even better. That's very cool. I'll keep my fingers crossed. =)

**Comment by mouse0270** [comment]
Oh god I didn't realize I needed chain signs until now...
