### ISSUE TITLE
Expand Forge Compatibility 

### ISSUE THREAD

**Issue by mouse0270** [Yamahari/ILikeWood-1.15#29]
Consider adding the following tags to chest `<tag:items:forge:chests>` and `<tag:items:forge:chests/wooden>`  so that crafting recipes that use a chest as an input item can be identified using a forge tag instead of a very specific chest.

~~Forge adds the following tags to chests in default minecraft `<tag:items:forge:chests>` and `<tag:items:forge:chests/wooden>` so that crafting recipes can use that tag in crafting recipes. Your mod is missing these tags (I've added them via crafttweaker) so any recipe that uses `<tag:items:forge:chests>` or `<tag:items:forge:chests/wooden>` will not include your chest, which they probably should.~~

**Comment by mouse0270** [comment]
I've changed the title to better match the request as I've notice that apparently this is something that two mods just seemed to have accidently used and is not a standard provided from forge.

**Comment by Yamahari** [comment]
I will try to add this :) it was in at an earlier version but I haven't ported it yet
