### ISSUE TITLE
Problem between datapack and multiplayer

### ISSUE THREAD

**Issue by gfuxi** [Yamahari/ILikeWood-1.15#34]
Dear Yamahari!

I like your mod very much and especially the datapack to make it compadible with Biomes 'O Plenty is very nice!
Unfortunately, I discovered a problem, when using the datapack in a multiplayer session. I use the following setup:
* both players use MC 1.16.4
* both players have the identical set of mods
* both players use same versions of mods and the datapack for your mod
* use modversion: ilikewood-1.16.4-5.0.0.0
* used data pack version: ilikewood-1.16.4-5.0.0.0-biomesoplenty-datapack
* multiplayer on local LAN

When the second player is trying to connect to the session, the following error occures and the player gets disconnected
automatically:

_Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet -_
_size of 2206362 is larger than protocal maximum of 2097152_

Hope I gave you all information necessary for debugging the problem. Otherwise feel free to contact me under
gfuxi@posteo.de.
I would realy regret to remove your wonderfull mod from my modpack (Back in the Woods).

Thx and Best regards      Georg

**Comment by Yamahari** [comment]
heya, I am not sure what is causing this error. The datapack only adds the recipes and loot tables for the BoP stuff, so strictly speaking you don't really need it,  does it run without?
Also are you able to upgrade to 1.16.5 ? (should be no problem, not much has changed from 1.16.4 to 1.16.5). In the newest version you don't need the datapack at all, the BoP content is a seperate plugin then. :)
There's only one downside, if you created chests/barrels/lecterns from my mod before ilikewood-1.16.5-6.0.0.0, then updating will break all those blocks, i.e. they lose their content, so be sure to take all your stuff out before you upgrade!
