### ISSUE TITLE
Oak beds display only bottom half of bed when placed.

### ISSUE THREAD

**Issue by danemorgan** [Yamahari/ILikeWood-1.15#39]
I haven't tried any of the other types yet, but I made some oak beds and they display the bottom half of the bed only. The top half is invisible. You can still sleep in the bed, but if you walk on top of it, you get stuck like you do in boats sometimes.

**Comment by Yamahari** [comment]
what version?

**Comment by danemorgan** [comment]
Minecraft - 1.16.5
Forge - 36.1.31
ILW - ilikewood-1.16.5-6.3.0.0.jar

**Comment by danemorgan** [comment]
By top half and bottom half, I mean head and foot. Sorry. I should have worded that better.
