### ISSUE TITLE
Having this crash after adding i like wood to my pack

### ISSUE THREAD

**Issue by Mr-Syntax** [Yamahari/ILikeWood-1.15#43]
[crash-2021-10-05_05.33.27-server.txt](https://github.com/Yamahari/ILikeWood-1.15/files/7282580/crash-2021-10-05_05.33.27-server.txt)

i would really like to include the mod in this pack

https://www.curseforge.com/minecraft/modpacks/chosencraft

**Comment by Yamahari** [comment]
I cant support optifine builds, maybe try without optifine

**Comment by Mr-Syntax** [comment]
:-{ sad i dont know much about coding and stuff, but what exactly is it you have to do extra to support optifine? is it doing something to the textures? code? im curious
