### ISSUE TITLE
Fishing rods & crossbows have odd behavior

### ISSUE THREAD

**Issue by triggerhurt** [Yamahari/ILikeWood-1.15#47]
Currently running forge 39.0.66, tested in single player
I noticed the following problems when testing this mod in survival mode (didn't think it was necessary to submit a separate issue for all of them):

1. New fishing rods simply don't work: Upon casting, the fishing rod immediately resets itself, rendering it useless for the time being.
2. New crossbows have a vertically-inverted draw animation: The frames are there, and it still technically works fine, but it looks pretty bizarre. When at rest, loaded or not, the crossbows look fine.

**Comment by Yamahari** [comment]
Hi, there's a PR to Forge that allows custom fishing rods to work again. For the crossbow animation there no fix atm, need to make a custom PR to Forge first x)

**Comment by triggerhurt** [comment]
Ah, understood. Thank you for the timely reply.

**Comment by Yamahari** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/8424
for reference

**Comment by Yamahari** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/8625

**Comment by Yamahari** [comment]
fixed in 9.0.0.0
