### ISSUE TITLE
All custom tiered tools use the wooden tool durability bar

### ISSUE THREAD

**Issue by triggerhurt** [Yamahari/ILikeWood-1.15#48]
All of these tools have the tag {Damage:50}. The top row are vanilla swords, the bottom row are their birch equivalents provided by this mod.
![image](https://user-images.githubusercontent.com/32649483/154320805-526fb642-3d8d-41bd-9fcb-fdb957b59397.png)

**Comment by Yamahari** [comment]
Only visually?

**Comment by triggerhurt** [comment]
Correct; their actual durability is still intact, but the visual durability bar behaves like it's a wooden tool. It's quite confusing to look at when playing with it, I often rely on taking a quick peek down at my tool's durability in my hotbar to know if i should stop using it

**Comment by Yamahari** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/8482

**Comment by Yamahari** [comment]
should be fixed as PR is merged
