### ISSUE TITLE
Fails to load in newest forge versions

### ISSUE THREAD

**Issue by Nalwyn603** [Yamahari/ILikeWood-1.15#50]
I've been troubleshooting my mods and have found both 1.18.x versions of the mod get the "failed to load correctly" in the newest versions of forge 1.18.2; this was the only mod in the folder

**Comment by Yamahari** [comment]
they are both marked as 1.18.1 x) That being said they should work for 1.18.2 unless some breaking change was introduced during 1.18.2, I'll have a look when I update the mod next time

**Comment by Yamahari** [comment]
Now on 1.18.2, note the new config mods
