### ISSUE TITLE
Please fix this issue

### ISSUE THREAD

**Issue by Pawccy** [Yamahari/ILikeWood-1.15#52]
The mod's great-- but having every single feature be a separate jar file is horrendous, there are better ways to make a mod configurable, please fix this, it would be great if it was just one or two files and nothing else. why do i have to download 17 different files to get the full experience when mods like quark can do it in one.

**Comment by Yamahari** [comment]
Hi, it will stay as is. You only need to download them once for every MC version, you don't need to download them everytime I update the main mod (it takes me 30s to do this) :) Also there will be a configurator website that'll download everything for you.
