### ISSUE TITLE
The new 'config' system does not work with Curseforge

### ISSUE THREAD

**Issue by ChiefArug** [Yamahari/ILikeWood-1.15#54]
Curseforge only allows one file per project in modpacks, and so you cannot install more than one 'config' mod.

https://user-images.githubusercontent.com/73862885/164613345-85a27401-0c74-433a-bbf0-09c89bd5a5bd.mp4

Even if you add them manually to the mods folder you cannot export it to upload to the site.
Please, use a normal config file like other mods. This system cannot reasonably work.

**Comment by Yamahari** [comment]
fixed with 9.0.0.0, now file based

**Comment by TheTimTimJr** [comment]
Can You make it file based for 1.18.2?
