### ISSUE TITLE
Crash when leaving render distance with Coloured Campfire

### ISSUE THREAD

**Issue by complicitsalami** [Yamahari/ILikeWood-1.15#57]
Hi there, 

Really enjoying the new coloured campfires, they are a really neat feature of the mod. I was playing on my server with I Like Wood (latest version) installed and ran into a crash when going away from / unloading a chunk that had a purple campfire. I have added a pastebin below:

https://pastebin.com/YegbCAUM

**Comment by Yamahari** [comment]
Hi, glad you like the mod.
I see you have optifine installed, can you check if it happens without optifine?

**Comment by Yamahari** [comment]
i found the potential issue, i have a fix for it in the next version, although I am not sure if that edge case can ever occur without optifine x)

**Comment by complicitsalami** [comment]
I tried without Optifine and didn't run into the issue so looks like it was just due to Optifine being used. Thanks for letting me know, I just removed optifine as I would prefer this mod 👍

**Comment by Yamahari** [comment]
added a fix for this in the newest version, don't take it as a precedence though, i will generally not fix issues introduced by optifine x)
