### ISSUE TITLE
Error loading mods: I Like Wood has failed to load correctly

### ISSUE THREAD

**Issue by KAARVAAH** [Yamahari/ILikeWood-1.15#65]
Minecraft 1.20.1
Forge 47.2.0
log and crash report: https://pastebin.com/P7tQymQS ; (crash report https://pastebin.com/bW3UA5rU)
I launch the game and i got this error:
![image](https://github.com/Yamahari/ILikeWood/assets/150563243/68d1b9c8-8d99-4031-bab1-3f2e75858b88)
someone could help me please?

**Comment by Buhoy37** [comment]
How did you solve the problem?
